"""empty message

Revision ID: 15f1edd454cf
Revises: 79461027ab50
Create Date: 2024-05-05 09:30:55.523415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f1edd454cf'
down_revision = '79461027ab50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physician', schema='proposal') as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physician', schema='proposal') as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
