"""empty message

Revision ID: 79461027ab50
Revises: 705a416c2d4f
Create Date: 2024-05-05 07:18:04.913603

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '79461027ab50'
down_revision = '705a416c2d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physician', schema='proposal') as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    
    op.execute("UPDATE proposal.physician physician SET geom = geoms.geom FROM (select p.id, ST_TRANSFORM(g.geomout, 4326) geom FROM proposal.physician p CROSS JOIN geocode(p.address, 1) g) geoms WHERE geoms.id = physician.id")

    with op.batch_alter_table('zip_code', schema='proposal') as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))

    op.execute("UPDATE proposal.zip_code z SET geom = geography('point(' || z.longitude || ' ' || z.latitude || ')')::geometry")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zip_code', schema='proposal') as batch_op:
        batch_op.drop_index('idx_zip_code_geom', postgresql_using='gist')
        batch_op.drop_column('geom')

    with op.batch_alter_table('physician', schema='proposal') as batch_op:
        batch_op.drop_index('idx_physician_geom', postgresql_using='gist')
        batch_op.drop_column('geom')

    # ### end Alembic commands ###
